# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans tes services
        autoconfigure: true # Enregistre automatiquement tes services en tant que commandes, abonnés aux événements, etc.

    # Les classes dans le dossier src/ sont automatiquement disponibles comme services
    # Cette configuration crée un service pour chaque classe dont l'ID est le nom de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Si tu as d'autres services personnalisés, tu peux les définir explicitement ici


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
